workflow:
    rules:
        - if: $CI_MERGE_REQUEST_ID
        - when: always

before_script:
    - python --version

stages:
    - Test

run_tests:
    stage: Test
    tags:
        - rzgenie
        - shell
    script:
        - python mili_reader_test.py