workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "web"
      when: always
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TITLE =~ /^(\[Draft\]|\(Draft\)|Draft:)/
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - when: never

variables:
    SYS_PYTHON_BIN: "/usr/tce/packages/python/python-3.7.2/bin/python3"
    PIP_ARGS: "--no-cache --find-links=https://www-lc.llnl.gov/python/wheelhouse"
    VENV_NAME: "venv-mili-python-3.7.2"
    MINIMUM_COVERAGE: "86"
    INSTALL_ROOT: "/collab/usr/gapps/mdg/python/"

stages:
    - test
    - deploy

before_script:
    - freturn() { return "$1" ; }
    - module load python/3.7.2
    - python3 --version
    - ${SYS_PYTHON_BIN} -m venv ${VENV_NAME}
    - source ${VENV_NAME}/bin/activate
    - pip3 install --upgrade pip # need newer pip to build numpy on rz
    - pip3 install ${PIP_ARGS} -e .

unit_tests:
    stage: test
    tags:
        - rzgenie
        - shell
    script:
        - cd src
        - srun -n1 -A wbronze -p pdebug python3 -m unittest tests.reader_test

coverage:
    stage: test
    tags:
        - rzgenie
        - shell
    script:
        - cd src
        - python3 -m coverage --version
        - srun -n1 python3 -m coverage run -m unittest tests.reader_test
        # avoid failure if there are not multiple reports
        - python3 -m coverage combine || freturn 0
        - python3 -m coverage xml
        - python3 -m coverage report --fail-under=$MINIMUM_COVERAGE --omit=mili/grizinterface.py
    artifacts:
        when: always
        paths:
            - src/coverage.xml
        reports:
            coverage_report:
                coverage_format: cobertura
                path: src/coverage.xml
        expire_in: 1 week
    coverage: '/TOTAL.+?([0-9]+\%)$/'

stage-release:
    stage: deploy
    tags:
        - rzgenie
        - shell
    script:
        - pip3 install --upgrade build
        - python3 -m build

# TODO(wrt): make this actually deploy
# deploy-release:
#     stage: deploy
#     tags:
#         - rzgenie
#         - shell
#     script:
#         - version=$(cat src/mili/__init__.py | grep 'version' | grep -Eo "[[:digit:]]+,[[:digit:]]+,[[:digit:]]+" | tr , . )
#         - git tag -a v${version} -m "version $version"
#         - git push origin v${version}
#         - pip3 install --upgrade build
#         - python3 -m build
#         - cp -n dist/* ${INSTALL_ROOT}/wheels/
#     rules:
#         - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#           when: manual

