[tox]
requires =
  tox>=4
env_list = unittest, py{38,39,310,311,312,313}

[testenv]
description = Run unittest
commands =
  python -m unittest discover tests

[testenv:unittest]
basepython = /usr/tce/packages/python/python-3.13.2/bin/python3

[testenv:py38]
basepython = /usr/bin/python3.8

[testenv:py39]
basepython = /usr/tce/packages/python/python-3.9.12/bin/python3

[testenv:py310]
basepython = /usr/tce/packages/python/python-3.10.8/bin/python3

[testenv:py311]
basepython = /usr/tce/packages/python/python-3.11.5/bin/python3

[testenv:py312]
basepython = /usr/tce/packages/python/python-3.12.2/bin/python3

[testenv:py313]
basepython = /usr/tce/packages/python/python-3.13.2/bin/python3
