"""Common values defined by MDG's simulation codes in Mili databases.

NOTE: These enumerations are intended only for external use as a convenience
      for users. The two caveats to this are:
        - type hinting: Anywhere these are used for type hinting, the imports
                        should only be made in an "if TYPE_CHECKING" block
        - The derived variable specifications in derived.py

NOTE: These enumerations cover the known default naming of things by MDG's
      simulation codes. There is no requirement that these will remain the
      same in the future. Many of these names have changed in the past and
      we will try our best to keep them up to date.

SPDX-License-Identifier: (MIT)
"""

from __future__ import annotations
from enum import Enum
from typing import Union

def mdg_enum_to_string(enum_value: Union[str,EntityType,StateVariableName]) -> str:
    as_str: str
    if isinstance(enum_value, (EntityType,StateVariableName)):
      as_str = enum_value.value
    else:
      as_str = enum_value
    return as_str

class EntityType(Enum):
    """Common entity types output by MDG codes.

    NOTE: This does not cover all entity types that are output by MDG's codes.
    """
    GLOBAL = "glob"
    MATERIAL = "mat"
    NODE = "node"
    BRICK = "brick"
    BEAM = "beam"
    SHELL = "shell"
    QUAD = "quad"
    TSHELL = "tshell"
    DISC = "disc"
    DELAM = "delam"
    COHESIVE = "cohesive"
    PARTICLE = "particle"
    MESHLESS = "ml"
    NODAL_TET = "ntet"
    HEX62 = "hex62"
    WALL = "wall"
    THICK = "thick"
    SAND = "sand"
    CONTACT_SEGMENT = "cseg"
    PRESSURE_SEGMENT = "pseg"
    MGROUP = "mgroup"
    LOADCURVE = "lcurve"
    SPHERAL = "sph"
    AIRBAG = "airbag"
    FSEG = "fseg"
    TET = "tet"
    LEDSEG = "ledseg"
    TET10 = "tet10"

class StateVariableName(Enum):
    """Common State variables output by MDG codes."""
    pass

class Dyna3dStateVariables(StateVariableName):
    """State variables only written by Dyna3d."""
    SHELL_EFF_PLASTIC_STRAIN_MID = "eeff_mid"
    SHELL_EFF_PLASTIC_STRAIN_IN = "eeff_in"
    SHELL_EFF_PLASTIC_STRAIN_OUT = "eeff_out"
    MIN_PRESSURE = "min_press"
    MAX_PRESSURE = "max_press"
    MIN_PRINCIPAL_1 = "min_prin1"
    MAX_PRINCIPAL_1 = "max_prin1"
    MIN_PRINCIPAL_3 = "min_prin3"
    MAX_PRINCIPAL_3 = "max_prin3"
    MAX_MISES = "max_mises"
    GLOBAL_RIGID_BODY_X_VEL = "rbvx"
    GLOBAL_RIGID_BODY_Y_VEL = "rbvy"
    GLOBAL_RIGID_BODY_Z_VEL = "rbvz"

class DiabloStateVariables(StateVariableName):
    """State variables only written by Diablo."""
    SHELL_EFF_PLASTIC_STRAIN_MID = "eps_mid"
    SHELL_EFF_PLASTIC_STRAIN_IN = "eps_in"
    SHELL_EFF_PLASTIC_STRAIN_OUT = "eps_out"
    GLOBAL_RIGID_BODY_X_VEL = "rigx"
    GLOBAL_RIGID_BODY_Y_VEL = "rigy"
    GLOBAL_RIGID_BODY_Z_VEL = "rigz"
    NODAL_TEMPERATURE_RATE = "dtemp/dt"
    NODAL_EIGENVECTOR = "evec"

class GlobalStateVariables(StateVariableName):
    """Global (glob) variables"""
    KINETIC_ENERGY = "ke"
    KINETIC_ENERGY_PART = "ke_part"
    POTENTIAL_ENERGY = "pe"
    HOURGLASS_ENERGY = "he"
    BULK_VIS_ENERGY = "bve"
    DRILL_SUPPRESSION_ENERGY = "dre"
    STIFFNESS_DAMPING_ENERGY = "stde"
    FRICTIONAL_LIKE_DAMPING_ENERGY = "flde"
    FREQUENCE_RANGE_DAMPING_ENERGY = "frde"
    TOTAL_CONTACT_DAMPING_ENERGY = "tcon_damp_eng"
    TOTAL_CONTACT_FRICTION_ENERGE = "tcon_fric_eng"
    TOTAL_CONTACT_ENERGY = "tcon_eng"
    EXTERNAL_WORK = "ew"
    TOTAL_ENERGY = "te"
    DYNA_RIGID_BODY_X_VEL = "rbvx"
    DYNA_RIGID_BODY_Y_VEL = "rbvy"
    DYNA_RIGID_BODY_Z_VEL = "rbvz"
    DIABLO_RIGID_BODY_X_VEL = "rigx"
    DIABLO_RIGID_BODY_Y_VEL = "rigy"
    DIABLO_RIGID_BODY_Z_VEL = "rigz"
    RIGID_BODY_X_ACC = "rbax"
    RIGID_BODY_Y_ACC = "rbay"
    RIGID_BODY_Z_ACC = "rbaz"
    TOTAL_DALAMBERT_X_FORCE = "g_dalembert_fx"
    TOTAL_DALAMBERT_Y_FORCE = "g_dalembert_fy"
    TOTAL_DALAMBERT_Z_FORCE = "g_dalembert_fz"
    TOTAL_DALAMBERT_X_MOMENT = "g_dalembert_mx"
    TOTAL_DALAMBERT_Y_MOMENT = "g_dalembert_my"
    TOTAL_DALAMBERT_Z_MOMENT = "g_dalembert_mz"

class MaterialStateVariables(StateVariableName):
    """Material (mat) variables"""
    POTENTIAL_ENERGY = "matpe"
    KINETIC_ENERGY = "matke"
    HOURGLASS_ENERGY = "mathe"
    BULK_VIS_ENERGY = "matbve"
    DRILL_DOF_ENERGY = "matdre"
    STIFFNESS_DAMPING_ENERGY = "matstde"
    FRICTIONAL_LIKE_DAMPING_ENERGY = "matflde"
    FREQUENCY_RANGE_DAMPING_ENERGY = "matfrde"
    TOTAL_ENERGY = "matte"
    MASS = "matmass"
    CENTER_OF_GRAVITY_X_POSITION = "matcgx"
    CENTER_OF_GRAVITY_Y_POSITION = "matcgy"
    CENTER_OF_GRAVITY_Z_POSITION = "matcgz"
    CENTER_OF_GRAVITY_X_VELOCITY = "matxv"
    CENTER_OF_GRAVITY_Y_VELOCITY = "matyv"
    CENTER_OF_GRAVITY_Z_VELOCITY = "matzv"
    CENTER_OF_GRAVITY_X_ACCELERATION = "matxa"
    CENTER_OF_GRAVITY_Y_ACCELERATION = "matya"
    CENTER_OF_GRAVITY_Z_ACCELERATION = "matza"
    X_MOMENTUM = "matmvx"
    Y_MOMENTUM = "matmvy"
    Z_MOMENTUM = "matmvz"
    MOMENTUM_MAGNITUDE = "matmv"
    X_CONTACT_FORCE = "con_forx"
    Y_CONTACT_FORCE = "con_fory"
    Z_CONTACT_FORCE = "con_forz"
    X_CONTACT_MOMENT = "con_momx"
    Y_CONTACT_MOMENT = "con_momy"
    Z_CONTACT_MOMENT = "con_momz"
    DAMPING_ENERGY = "con_damp_eng"
    FRICTION_ENERGY = "con_fric_eng"
    CONTACT_ENERGY = "con_eng"

class NodalStateVariables(StateVariableName):
    """Nodal (node) variables"""
    NODAL_POSITION = "nodpos"
    X_POSITION = "ux"
    Y_POSITION = "uy"
    Z_POSITION = "uz"
    NODAL_VELOCITY = "nodvel"
    X_VELOCITY = "vx"
    Y_VELOCITY = "vy"
    Z_VELOCITY = "vz"
    NODAL_ACCELERATION = "nodacc"
    X_ACCELERATION = "ax"
    Y_ACCELERATION = "ay"
    Z_ACCELERATION = "az"
    ROTATIONAL_DISPLACEMENT = "rotdis"
    X_ANGLE = "rux"
    Y_ANGLE = "ruy"
    Z_ANGLE = "ruz"
    ROTATIONAL_VELOCITY = "rotvel"
    X_ANGLE_VELOCITY = "rvx"
    Y_ANGLE_VELOCITY = "rvy"
    Z_ANGLE_VELOCITY = "rvz"
    ROTATIONAL_ACCELERATION = "rotacc"
    X_ANGLE_ACCELERATION = "rax"
    Y_ANGLE_ACCELERATION = "ray"
    Z_ANGLE_ACCELERATION = "raz"
    TEMPERATURE = "temp"
    FRICTIONAL_WORK = "frwk"
    REACTION_MOMENT = "remom"
    X_REACTION_MOMENT = "remomx"
    Y_REACTION_MOMENT = "remomy"
    Z_REACTION_MOMENT = "remomz"
    REACTION_FORCE = "refrc"
    X_REACTION_FORCE = "refrcx"
    Y_REACTION_FORCE = "refrcy"
    Z_REACTION_FORCE = "refrcz"
    X_DALAMBERT_FORCE = "dalambert_fx"
    Y_DALAMBERT_FORCE = "dalambert_fy"
    Z_DALAMBERT_FORCE = "dalambert_fz"
    X_TANGENTIAL_TRACTION = "nodtang_x"
    Y_TANGENTIAL_TRACTION = "nodtang_y"
    Z_TANGENTIAL_TRACTION = "nodtang_z"

class LoadCurveStateVariables(StateVariableName):
    """Loadcurve (lcurve) variables"""
    LC_FUNCTION = "lcfunc"
    REACTION_FORCE = "recfrc"
    X_FORCE = "x"
    Y_FORCE = "y"
    Z_FORCE = "z"
    X_MOMENT = "xm"
    Y_MOMENT = "ym"
    Z_MOMENT = "zm"

class BeamStateVariables(StateVariableName):
    """Beam (beam) variables"""
    AXIAL_FORCE = "axf"
    SHEAR_RESULTANT_S = "sfs"
    SHEAR_RESULTANT_T = "sft"
    BENDING_MOMENT_S = "ms"
    BENDING_MOMENT_T = "mt"
    MAX_EQUIV_PLASTIC_STRAIN = "max_eps"
    SVECTOR = "svec"
    X_SVECTOR = "svec_x"
    Y_SVECTOR = "svec_y"
    Z_SVECTOR = "svec_z"
    DISTRIBUTED_LOAD = "dist_load"
    X_DISTRIBUTED_LOAD = "dist_load_x"
    Y_DISTRIBUTED_LOAD = "dist_load_y"
    Z_DISTRIBUTED_LOAD = "dist_load_z"
    EFFECTIVE_STRESS_1 = "efs1"
    EFFECTIVE_STRESS_2 = "efs2"
    EFFECTIVE_PLASTIC_STRAIN_1 = "eps1"
    EFFECTIVE_PLASTIC_STRAIN_2 = "eps2"
    TORTIONAL_RESULTANT = "tor"

class DiscreteStateVariables(StateVariableName):
    """Discrete (disc) variables"""
    EXTENSION = "disc_ext"
    FORCE_MAGNITUDE = "disc_fmag"
    X_FORCE = "disc_fx"
    Y_FORCE = "disc_fy"
    Z_FORCE = "disc_fz"

class ShellStateVariables(StateVariableName):
    """Shell (shell) variables"""
    STRESS_MID = "stress_mid"
    STRESS_IN = "stress_in"
    STRESS_OUT = "stress_out"
    STRAIN_IN = "strain_in"
    STRAIN_OUT = "strain_out"
    DYNA_EFF_PLASTIC_STRAIN_MID = "eeff_mid"
    DYNA_EFF_PLASTIC_STRAIN_IN = "eeff_in"
    DYNA_EFF_PLASTIC_STRAIN_OUT = "eeff_out"
    DIABLO_EFF_PLASTIC_STRAIN_MID = "eps_mid"
    DIABLO_EFF_PLASTIC_STRAIN_IN = "eps_in"
    DIABLO_EFF_PLASTIC_STRAIN_OUT = "eps_out"
    EQUIV_PLASTIC_STRAIN = "eps"
    BENDING_RESULTANT = "bend"
    BEND_XX = "mxx"
    BEND_YY = "myy"
    BEND_ZZ = "mzz"
    SHEAR_RESULTANT = "shear"
    SHEAR_XX = "qxx"
    SHEAR_YY = "qyy"
    NORMAL_RESULTANT = "normal"
    NORMAL_XX = "nxx"
    NORMAL_YY = "nyy"
    NORMAL_ZZ = "nzz"
    THICKNESS = "thick"
    ELEMENT_VARIABLE_1 = "edv1"
    ELEMENT_VARIABLE_2 = "edv2"
    INTERAL_ENERGY = "inteng"

class ContactSegmentStateVariables(StateVariableName):
    """Contact Segment (cseg) variables"""
    NORMAL_PRESSURE = "sn"
    SHEAR_MAGNITUDE = "shmag"
    R_SHEAR = "sr"
    S_SHEAR = "ss"
    X_TRACTION = "s1"
    Y_TRACTION = "s2"
    Z_TRACTION = "s3"
    CONTACT_FRICTION_WORK = "seg_frwk"

class PressureSegmentStateVariables(StateVariableName):
    """Pressure Segment (pseg) variables"""
    PRESSURE_LOAD = "pload"
    SHEAR_LOAD = "sload"

class StressStrainStateVariables(StateVariableName):
    """The Stress/Strain state variables."""
    STRESS = "stress"
    X_STRESS = "sx"
    Y_STRESS = "sy"
    Z_STRESS = "sz"
    XY_STRESS = "sxy"
    YZ_STRESS = "syz"
    ZX_STRESS = "szx"
    STRAIN = "strain"
    X_STRAIN = "ex"
    Y_STRAIN = "ey"
    Z_STRAIN = "ez"
    XY_STRAIN = "exy"
    YZ_STRAIN = "eyz"
    ZX_STRAIN = "ezx"
    EQUIV_PLASTIC_STRAIN = "eps"
    EDRATE = "edrate"
    EPS_RATE = "eps_rate"

class ElementStateVariables(StateVariableName):
    """Common state variables shared by various entity types"""
    SAND_FLAG = "sand"
    ELEMENT_TIME_STEP = "tstep"
    ELEMENT_DELETION_CAUSE = "cause"

class DerivedVariables(StateVariableName):
    """Common Derived variables that can be calculated from MDG codes."""
    X_DISPLACEMENT = "disp_x"
    Y_DISPLACEMENT = "disp_y"
    Z_DISPLACEMENT = "disp_z"
    DISPLACEMENT_MAGNITUDE = "disp_mag"
    RADIAL_DISPLACEMENT_MAGNITUDE_XY = "disp_rad_mag_xy"
    X_VELOCITY = "vel_x"
    Y_VELOCITY = "vel_y"
    Z_VELOCITY = "vel_z"
    X_ACCELERATION = "acc_x"
    Y_ACCELERATION = "acc_y"
    Z_ACCELERATION = "acc_z"
    TANGENTIAL_TRACTION_MAGNITUDE = "nodtangmag"

    VOLUMETRIC_STRAIN = "vol_strain"
    PRINCIPAL_STRAIN_1 = "prin_strain1"
    PRINCIPAL_STRAIN_2 = "prin_strain2"
    PRINCIPAL_STRAIN_3 = "prin_strain3"
    PRINCIPAL_DEV_STRAIN_1 = "prin_dev_strain1"
    PRINCIPAL_DEV_STRAIN_2 = "prin_dev_strain2"
    PRINCIPAL_DEV_STRAIN_3 = "prin_dev_strain3"

    PRINCIPAL_STRAIN_1_ALT = "prin_strain1_alt"
    PRINCIPAL_STRAIN_2_ALT = "prin_strain2_alt"
    PRINCIPAL_STRAIN_3_ALT = "prin_strain3_alt"
    PRINCIPAL_DEV_STRAIN_1_ALT = "prin_dev_strain1_alt"
    PRINCIPAL_DEV_STRAIN_2_ALT = "prin_dev_strain2_alt"
    PRINCIPAL_DEV_STRAIN_3_ALT = "prin_dev_strain3_alt"

    PRINCIPAL_STRESS_1 = "prin_stress1"
    PRINCIPAL_STRESS_2 = "prin_stress2"
    PRINCIPAL_STRESS_3 = "prin_stress3"
    PRINCIPAL_DEV_STRESS_1 = "prin_dev_stress1"
    PRINCIPAL_DEV_STRESS_2 = "prin_dev_stress2"
    PRINCIPAL_DEV_STRESS_3 = "prin_dev_stress3"
    EFFECTIVE_STRESS = "eff_stress"
    PRESSURE = "pressure"
    MAX_SHEAR_STRESS = "max_shear_stress"

    TRIAXIALITY = "triaxiality"
    NORMALIZED_PRESSURE = "norm_press"
    EPS_RATE = "eps_rate"

    MAT_COG_DISP_X = "mat_cog_disp_x"
    MAT_COG_DISP_Y = "mat_cog_disp_y"
    MAT_COG_DISP_Z = "mat_cog_disp_z"

    ELEMENT_VOLUME = "element_volume"
    AREA = "area"

    SURFACE_STRAIN_X = "surfstrainx"
    SURFACE_STRAIN_Y = "surfstrainy"
    SURFACE_STRAIN_Z = "surfstrainz"
    SURFACE_STRAIN_XY = "surfstrainxy"
    SURFACE_STRAIN_YZ = "surfstrainyz"
    SURFACE_STRAIN_ZX = "surfstrainzx"